"""gas column

Revision ID: 8c5acf59b22a
Revises: a3c1e13e992c
Create Date: 2023-01-15 08:30:59.553481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5acf59b22a'
down_revision = 'a3c1e13e992c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallons_purchased', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpg', schema=None) as batch_op:
        batch_op.drop_column('gallons_purchased')

    # ### end Alembic commands ###
