"""inital migration

Revision ID: a3c1e13e992c
Revises: 
Create Date: 2023-01-15 06:45:59.121521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c1e13e992c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpg')
    # ### end Alembic commands ###
